######################################################################
# Automatically generated by qmake (2.01a) Wed Sep 3 03:39:59 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
INCLUDEPATH += /home/jesper/kde/include/marble

# Input
HEADERS += window.h
FORMS += window.ui
SOURCES += main.cpp window.cpp


LIBS += -L/home/jesper/kde/lib -lmarblewidget

